version: '3.8'

services:
  app:
    container_name: azeroth-fish-back
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:WANTAO9191@db:5432/azeroth-postgres
      # 请务必在生产环境中修改此密钥
      - AUTH_SECRET=x8z93m2kl10d8
    depends_on:
      - db

  db:
    container_name: azeroth-fish-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: WANTAO9191
      POSTGRES_DB: azeroth-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: